import { readFile, stat } from 'node:fs/promises'

const pkg = JSON.parse(await readFile('package.json', 'utf8'))
const patch = await readFile('cordis.patch.yml', 'utf8')
const client = await readFile('lib/client.js', 'utf8')
const host = await readFile('lib/index.js', 'utf8')
const manifest = JSON.parse(await readFile('vendor/manifest.json', 'utf8'))

const failures = []
if (pkg.name !== '@kiligzzz/dsh-kiligz-base') failures.push('package name mismatch')
if (pkg.dsh?.client?.platform !== 'web') failures.push('missing dsh.client.platform=web')
if (!patch.includes("name: '@kiligzzz/dsh-kiligz-base'")) failures.push('bundle patch has no base row')
if (patch.includes('dsh-kiligz-automation') || patch.includes('dsh-kiligz-better-sidebar')) failures.push('bundle patch must expose one base row, not child rows')
if (!client.includes('window.__ModuleLoader__.load({ id: "@kiligzzz/dsh-kiligz-base"')) failures.push('client is not a classic ModuleLoader bundle')
if (manifest.features?.length !== 7) failures.push('vendor manifest must describe seven features')
if (!client.includes('__dshKiligzFeatureFactories')) failures.push('client bundle does not compose feature factories')
if ((client.match(/window\.__ModuleLoader__\.load\(/g) ?? []).length !== 1) failures.push('client bundle must register exactly one ModuleLoader factory')
if (client.includes('accent-color:')) failures.push('client bundle must not use accent-color')
if (!client.includes('.cm-switch') || !client.includes('.dsh-st-switch')) failures.push('client bundle lacks scoped switch contracts')
if (!client.includes('--dsw-static-green-500')) failures.push('client bundle lacks green enabled switch state')
if (!client.includes('prefers-reduced-motion:reduce')) failures.push('client bundle lacks reduced-motion handling')
if (!client.includes('id: "automation", order: 2') || !client.includes('id: "skill", order: 3') || !client.includes('id: "mcp", order: 4') || !client.includes('id: `dsh-kiligz-base-${entry.id}`')) failures.push('client bundle lacks three independent footer entries')
if (client.includes('id: "scheduled-tasks"') || client.includes('id: "capabilities-skills"') || client.includes('id: "capabilities-mcp"')) failures.push('client bundle still exposes management Settings sections')
if (!host.includes('@goodandready/dsh-vision-bridge')) failures.push('host bundle lacks Vision Bridge integration')
if (!host.includes('"hybrid"')) failures.push('host bundle must default Vision Bridge to hybrid mode')
if (client.includes('VisionInputControls') || client.includes('👁️') || client.includes('+PDF')) failures.push('client bundle must not render Vision Bridge composer controls')
if (!client.includes('settings.plugin.item')) failures.push('client bundle lacks the Vision Bridge settings card')
if (client.includes('VisionSection')) failures.push('client bundle must replace the full Vision Bridge settings panel')
if (!client.includes('VisionSettingsPanel') || !client.includes('pickDictionary')) failures.push('client bundle lacks the trimmed localized Vision Bridge settings panel')
if (!client.includes('.dshAcField:not(:has(#auto-continue-paused))')) failures.push('client bundle must trim the auto-continue card to its master switch')
if (!client.includes('ctx.locale.register(NS, { en, ru, zh })')) failures.push('client bundle must register the Chinese Vision Bridge dictionary')
if (pkg.dependencies?.['dsh-vision-router'] !== undefined || patch.includes('dsh-vision-router') || host.includes('dsh-vision-router') || client.includes('dsh-vision-router')) failures.push('dsh-vision-router must be absent from package metadata and build artifacts')
if (!client.includes('return { apply: module.exports.apply, inject: module.exports.inject }')) failures.push('client factory export is incomplete')
if (!client.includes('/capabilities-api/skill/open-directory')) failures.push('client bundle lacks open Skill directory action')
if (client.includes('}, "✎")') || client.includes('}, "🗑")') || client.includes('}, "⟳")') || client.includes('? "▾" : "▸"') || client.includes('"⟳ 刷新全部工具"')) failures.push('client bundle still contains legacy action glyphs')
for (const path of ['lib/index.js', 'lib/client.js', 'assets/mcp-link.svg']) {
  try { await stat(path) } catch { failures.push(`missing ${path}`) }
}
if (failures.length > 0) throw new Error(`dsh-kiligz-base verify failed:\n- ${failures.join('\n- ')}`)
console.log('dsh-kiligz-base verification passed')
