import { readFile, stat } from 'node:fs/promises'

const pkg = JSON.parse(await readFile('package.json', 'utf8'))
const patch = await readFile('cordis.patch.yml', 'utf8')
const client = await readFile('lib/client.js', 'utf8')
const host = await readFile('lib/index.js', 'utf8')
const manifest = JSON.parse(await readFile('vendor/manifest.json', 'utf8'))

const failures = []
if (pkg.name !== '@kiligzzz/dsh-kiligz-base') failures.push('package name mismatch')
if (pkg.dsh?.client?.platform !== 'web') failures.push('missing dsh.client.platform=web')
if (!patch.includes("name: '@kiligzzz/dsh-kiligz-base'")) failures.push('bundle patch has no base row')
if (patch.includes('dsh-kiligz-automation') || patch.includes('dsh-kiligz-better-sidebar')) failures.push('bundle patch must expose one base row, not child rows')
if (!client.includes('window.__ModuleLoader__.load({ id: "@kiligzzz/dsh-kiligz-base"')) failures.push('client is not a classic ModuleLoader bundle')
if (manifest.features?.length !== 5) failures.push('vendor manifest must describe five features')
if (pkg.dependencies?.['dsh-better-sidebar'] !== undefined || host.includes('dsh-better-sidebar') || client.includes('dsh-better-sidebar')) failures.push('dsh-better-sidebar must be absent from package metadata and build artifacts')
if (pkg.dependencies?.['dsh-client-auto-continue'] !== undefined || host.includes('dsh-client-auto-continue') || client.includes('auto-continue')) failures.push('auto-continue must be absent from package metadata and build artifacts')
if (!client.includes('__dshKiligzFeatureFactories')) failures.push('client bundle does not compose feature factories')
if ((client.match(/window\.__ModuleLoader__\.load\(/g) ?? []).length !== 1) failures.push('client bundle must register exactly one ModuleLoader factory')
if (client.includes('accent-color:')) failures.push('client bundle must not use accent-color')
if (!client.includes('.cm-switch') || !client.includes('.dsh-st-switch')) failures.push('client bundle lacks scoped switch contracts')
if (!client.includes('--dsw-static-green-500')) failures.push('client bundle lacks green enabled switch state')
if (!client.includes('prefers-reduced-motion:reduce')) failures.push('client bundle lacks reduced-motion handling')
if (!client.includes('id: "automation", order: 2') || !client.includes('id: "skill", order: 3') || !client.includes('id: "mcp", order: 4') || !client.includes('id: `dsh-kiligz-base-${entry.id}`')) failures.push('client bundle lacks three independent footer entries')
if (client.includes('id: "scheduled-tasks"') || client.includes('id: "capabilities-skills"') || client.includes('id: "capabilities-mcp"')) failures.push('client bundle still exposes management Settings sections')
if (!host.includes('@goodandready/dsh-vision-bridge')) failures.push('host bundle lacks Vision Bridge integration')
if (pkg.dependencies?.['@modelcontextprotocol/sdk'] !== '1.30.0') failures.push('MCP OAuth SDK must be pinned to 1.30.0')
if (!host.includes('discoverOAuthServerInfo') || !host.includes('refreshAuthorization')) failures.push('host bundle lacks MCP OAuth broker')
if (!/headers\.Authorization\s*=\s*["']Bearer ["']\s*\+\s*grant\.accessToken/.test(host)) failures.push('host bundle lacks dynamic OAuth Bearer injection')
if (!client.includes('/capabilities-api/mcp/oauth/login') || !client.includes('OAuth（浏览器登录并自动刷新）')) failures.push('client bundle lacks MCP OAuth controls')
if (!host.includes('"hybrid"')) failures.push('host bundle must default Vision Bridge to hybrid mode')
if (client.includes('VisionInputControls') || client.includes('👁️') || client.includes('+PDF')) failures.push('client bundle must not render Vision Bridge composer controls')
if (!client.includes('settings.plugin.item')) failures.push('client bundle lacks the Vision Bridge settings card')
if (client.includes('VisionSection')) failures.push('client bundle must replace the full Vision Bridge settings panel')
if (!client.includes('VisionSettingsPanel') || !client.includes('pickDictionary')) failures.push('client bundle lacks the trimmed localized Vision Bridge settings panel')
if (!client.includes('ctx.locale.register(NS, { en, ru, zh })')) failures.push('client bundle must register the Chinese Vision Bridge dictionary')
if (pkg.dependencies?.['dsh-vision-router'] !== undefined || patch.includes('dsh-vision-router') || host.includes('dsh-vision-router') || client.includes('dsh-vision-router')) failures.push('dsh-vision-router must be absent from package metadata and build artifacts')
if (!client.includes('return { apply: module.exports.apply, inject: module.exports.inject }')) failures.push('client factory export is incomplete')
if (!client.includes('/capabilities-api/skill/open-directory')) failures.push('client bundle lacks open Skill directory action')
if (client.includes('ctx.slots.inject("conversation.input.left"') || client.includes('ctx.slots.inject("sidebar.workspaces"') || client.includes('ctx.slots.inject("sidebar.schedule"') || client.includes('ctx.slots.inject("settings.section"')) failures.push('client bundle still registers Automation or manager UI outside the base modal')
if (client.includes('}, "✎")') || client.includes('}, "🗑")') || client.includes('}, "⟳")') || client.includes('? "▾" : "▸"') || client.includes('"⟳ 刷新全部工具"')) failures.push('client bundle still contains legacy action glyphs')
for (const path of ['lib/index.js', 'lib/client.js', 'assets/mcp-link.svg']) {
  try { await stat(path) } catch { failures.push(`missing ${path}`) }
}
if (failures.length > 0) throw new Error(`dsh-kiligz-base verify failed:\n- ${failures.join('\n- ')}`)
console.log('dsh-kiligz-base verification passed')
